
services:
  postgres:
    container_name: db
    image: postgres-image:latest
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./data-pg:/var/lib/postgresql/data
    ports:
      - 5442:5432
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - my-network

  spring-app:
    container_name: api
    image: spring-app-image
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - my-network
networks:
  my-network:
    driver: bridge