spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/taskmanager
    username: my_user
    password: my_password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect